os: linux
addons:
  apt:
    packages:
      - fakeroot
      - debhelper
      - devscripts
      - dput
      - libffi-dev
      - libssl-dev
      - libdistro-info-perl
      - libparse-debcontrol-perl
env:
  - UPLOAD_PPA=demonchild2112/emacs
before_install:
  - openssl aes-256-cbc -K $encrypted_6899303fb979_key -iv $encrypted_6899303fb979_iv -in travis_gpg_pass.txt.enc -out travis_gpg_pass.txt -d
install:
  - cat travis_gpg_pass.txt | gpg --passphrase-fd 0 --import launchpad_gpg_key.asc
  - gpg --list-keys
script:
  - ./build.sh --upload
