os: linux
addons:
  apt:
    packages:
      - fakeroot
      - debhelper
      - libffi-dev
      - libssl-dev
env:
  - UPLOAD_PPA=demonchild2112/test
before_install:
  - openssl aes-256-cbc \
      -K $encrypted_6899303fb979_key \
      -iv $encrypted_6899303fb979_iv \
      -in travis_gpg_pass.txt.enc \
      -out travis_gpg_pass.txt \
      -d
install:
  - cat travis_gpg_pass.txt | gpg --import launchpad_gpg_key.asc --passphrase-fd 0
  - gpg --list-keys
script:
  - ./build.sh
